import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DialogContextProvider } from "@/context/DialogContext";
import DialogsContainer from "@/components/dialogs/DialogsContainer";
import Button from "@/ui/Button";
import { Github } from "lucide-react";
import Link from "next/link";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  h-screen w-full grid grid-cols-[300px,1fr] grid-rows-[64px,1fr]`}>
        <DialogContextProvider>
          <Header />
          <Sidebar />
          <main className="bg-zinc-950 p-2 overflow-y-auto"> {children}</main>
          <DialogsContainer />
        </DialogContextProvider>
      </body>
    </html>
  );
}
